version: '2'

services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: drupal
    volumes:
      - ./mysql-data:/var/lib/mysql
  php:
    image: d8empty
    volumes:
      - ./:/var/www/html
    ports:
      - 8081:80
    links:
      - mysql